$(function() {
  $(".reveal-js").click(function(){
    $(".def-show-js").toggle();
    $(".def-hide-js").toggle();
  });
  $(".hide-def-js").click(function(){
    $(".def-show-js").toggle();
    $(".def-hide-js").toggle();
  });
  $(".reveal-op").click(function(){
    $(".def-show-op").toggle();
    $(".def-hide-op").toggle();
  });
  $(".hide-def-op").click(function(){
    $(".def-show-op").toggle();
    $(".def-hide-op").toggle();
  });
  $(".reveal-va").click(function(){
    $(".def-show-va").toggle();
    $(".def-hide-va").toggle();
  });
  $(".hide-def-va").click(function(){
    $(".def-show-va").toggle();
    $(".def-hide-va").toggle();
  });
  $(".reveal-vnc").click(function(){
    $(".def-show-vnc").toggle();
    $(".def-hide-vnc").toggle();
  });
  $(".hide-def-vnc").click(function(){
    $(".def-show-vnc").toggle();
    $(".def-hide-vnc").toggle();
  });
  $(".reveal-fu").click(function(){
    $(".def-show-fu").toggle();
    $(".def-hide-fu").toggle();
  });
  $(".hide-def-fu").click(function(){
    $(".def-show-fu").toggle();
    $(".def-hide-fu").toggle();
  });
  $(".reveal-me").click(function(){
    $(".def-show-me").toggle();
    $(".def-hide-me").toggle();
  });
  $(".hide-def-me").click(function(){
    $(".def-show-me").toggle();
    $(".def-hide-me").toggle();
  });
  $(".reveal-arg").click(function(){
    $(".def-show-arg").toggle();
    $(".def-hide-arg").toggle();
  });
  $(".hide-arg").click(function(){
    $(".def-show-arg").toggle();
    $(".def-hide-arg").toggle();
  });
  $(".reveal-pm").click(function(){
    $(".def-show-pm").toggle();
    $(".def-hide-pm").toggle();
  });
  $(".hide-pm").click(function(){
    $(".def-show-pm").toggle();
    $(".def-hide-pm").toggle();
  });
  $(".reveal-re").click(function(){
    $(".def-show-re").toggle();
    $(".def-hide-re").toggle();
  });
  $(".hide-re").click(function(){
    $(".def-show-re").toggle();
    $(".def-hide-re").toggle();
  });
  $(".reveal-ch").click(function(){
    $(".def-show-ch").toggle();
    $(".def-hide-ch").toggle();
  });
  $(".hide-ch").click(function(){
    $(".def-show-ch").toggle();
    $(".def-hide-ch").toggle();
  });
  $(".reveal-str").click(function(){
    $(".def-show-str").toggle();
    $(".def-hide-str").toggle();
  });
  $(".hide-str").click(function(){
    $(".def-show-str").toggle();
    $(".def-hide-str").toggle();
  });
  $(".reveal-bool").click(function(){
    $(".def-show-bool").toggle();
    $(".def-hide-bool").toggle();
  });
  $(".hide-bool").click(function(){
    $(".def-show-bool").toggle();
    $(".def-hide-bool").toggle();
  });
  $(".reveal-und").click(function(){
    $(".def-show-und").toggle();
    $(".def-hide-und").toggle();
  });
  $(".hide-und").click(function(){
    $(".def-show-und").toggle();
    $(".def-hide-und").toggle();
  });
  $(".reveal-NaN").click(function(){
    $(".def-show-NaN").toggle();
    $(".def-hide-NaN").toggle();
  });
  $(".hide-NaN").click(function(){
    $(".def-show-NaN").toggle();
    $(".def-hide-NaN").toggle();
  });
  $(".reveal-esc").click(function(){
    $(".def-show-esc").toggle();
    $(".def-hide-esc").toggle();
  });
  $(".hide-esc").click(function(){
    $(".def-show-esc").toggle();
    $(".def-hide-esc").toggle();
  });
  $(".reveal-al").click(function(){
    $(".def-show-al").toggle();
    $(".def-hide-al").toggle();
  });
  $(".hide-al").click(function(){
    $(".def-show-al").toggle();
    $(".def-hide-al").toggle();
  });
  $(".reveal-com").click(function(){
    $(".def-show-com").toggle();
    $(".def-hide-com").toggle();
  });
  $(".hide-com").click(function(){
    $(".def-show-com").toggle();
    $(".def-hide-com").toggle();
  });
  $(".reveal-jq").click(function(){
    $(".def-show-jq").toggle();
    $(".def-hide-jq").toggle();
  });
  $(".hide-jq").click(function(){
    $(".def-show-jq").toggle();
    $(".def-hide-jq").toggle();
  });
  $(".reveal-attr").click(function(){
    $(".def-show-attr").toggle();
    $(".def-hide-attr").toggle();
  });
  $(".hide-attr").click(function(){
    $(".def-show-attr").toggle();
    $(".def-hide-attr").toggle();
  });
});
